Repository SoEasyTeam/Dev.Town, pull requests merged in 2022-07, with the labels that each got.

#23 Feat & Style: Splash screen page
  src/App.jsx
  src/assets/full-logo.png
  src/assets/kakao.png
  src/assets/logo-white.png
  src/components/loginOptions/LoginOptions.jsx
  src/components/splash/Splash.jsx
  src/pages/SplashPage.jsx
Labels: feat, style

#27 Style: border 색상 변경
  src/components/common/Comment.jsx
Labels: style

#35 Common components 이슈 해결 및 속성 변경
  src/components/common/HomeImgPost.jsx
  src/components/common/HomePost.jsx
  src/components/common/Product.jsx
  src/components/common/TabMenu.jsx
  src/components/common/TopNav.jsx
Labels: style

#38 HomePost 및 ProductPrice 속성 값 수정
  src/components/common/HomeImgPost.jsx
  src/components/common/HomePost.jsx
  src/components/common/Product.jsx
Labels: style

#39 HomePost 및 HomeImgPost style 속성 수정
  src/components/common/HomeImgPost.jsx
  src/components/common/HomePost.jsx
Labels: style

#40 Refactor : Button 컴포넌트 수정
  src/components/common/Buttons.jsx
Labels: refactoring

#46 Common components 탑네비 및 탭 메뉴 속성 값 수정
  src/components/common/TabMenu.jsx
  src/components/common/TopNav.jsx
Labels: style

#51 profile setting page를 완성하였습니다. login 공부를 위해 devlop 브랜치로 병합 요청합니다.
  .prettierrc.js
  src/App.jsx
  src/assets/icon-home-fill.png
  src/assets/icon-message-circle-fill.png
  src/assets/icon-user-fill.png
  src/assets/upload-file.png
  src/components/common/Buttons.jsx
  src/components/common/Comment.jsx
  src/components/common/DeleteAlert.jsx
  src/components/common/HomeImgPost.jsx
  src/components/common/HomePost.jsx
  src/components/common/ProfileButtons.jsx
  src/components/common/TabMenu.jsx
  src/components/common/TopNav.jsx
  src/components/common/UserSearch.jsx
  src/components/loginOptions/LoginOptions.jsx
  src/components/splash/Splash.jsx
  src/pages/ProfileSettingPage.jsx
  src/pages/SplashPage.jsx
Labels: style

#54 Add product UI 구현
  src/components/common/TextAciveInput.jsx
  src/pages/AddProductPage.jsx
  src/pages/HomePage.jsx
Labels: style

#66 로그인 기능 구현 완료 예외처리 제외
  package-lock.json
  package.json
  src/App.jsx
  src/components/loginOptions/LoginOptions.jsx
  src/index.js
  src/pages/JoinMembershipPage.jsx
  src/pages/LoginPage.jsx
  src/pages/ProfileSettingPage.jsx
  src/pages/SplashPage.jsx
  src/redux/actions/authenticateAction.js
  src/redux/actions/joinAction.js
  src/redux/reducers/authenticateReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/joinReducer.js
  src/redux/store.js
Labels: feat

#71 홈페이지 포스트 div에서 Link로 변경
  src/components/common/HomeImgPost.jsx
  src/components/common/HomePost.jsx
Labels: style

#74 로그인 리듀서 값 수정
  src/redux/actions/authenticateAction.js
  src/redux/reducers/authenticateReducer.js
Labels: feat

#77 UserProfile 네비게이션 연결 및 feature/AddProduct 초기세팅
  src/App.jsx
  src/components/common/Buttons.jsx
  src/components/common/TabMenu.jsx
  src/components/home/HomeNoFollower.jsx
  src/features/UserProduct.jsx
  src/features/UserProfile.jsx
  src/pages/HomePage.jsx
  src/pages/MyProfile.jsx
  src/redux/actions/authenticateAction.js
  src/redux/actions/homeFeedAction.js
  src/redux/actions/profileAction.js
  src/redux/reducers/index.js
  src/redux/reducers/profileReducer.js
Labels: feat

#79 상품 추가 기능 구현 img제외 및 예외처리 X
  src/App.jsx
  src/components/common/TopNav.jsx
  src/features/UserProfile.jsx
  src/pages/AddProductPage.jsx
  src/redux/actions/addProductAction.js
  src/redux/reducers/addProductReducer.js
  src/redux/reducers/index.js
Labels: feat

#82 홈페이지 구현 완료 및 HomeImgPost 수정
  src/components/common/HomeImgPost.jsx
  src/components/home/HomeFeedBox.jsx
  src/pages/HomePage.jsx
  src/redux/actions/homeFeedAction.js
  src/redux/reducers/addProductReducer.js
  src/redux/reducers/authenticateReducer.js
  src/redux/reducers/homeFeedReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/joinReducer.js
  src/redux/reducers/profileReducer.js
Labels: feat

#96 Feat: 상품 등록 기능 구현 완료
  src/components/common/Buttons.jsx
  src/components/home/HomeFeedBox.jsx
  src/components/profile/UserPost.jsx
  src/pages/AddProductPage.jsx
  src/pages/LoginPage.jsx
  src/redux/actions/addProductAction.js
Labels: feat, style

#97 Perf: 로그인 예외처리
  src/App.jsx
  src/components/common/HomeImgPost.jsx
  src/components/common/HomePost.jsx
  src/components/home/HomeFeedBox.jsx
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
  src/pages/PostPage.jsx
Labels: feat, style

#98 login 예외처리 및 로컬스토리지 토큰 저장
  src/App.jsx
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
  src/redux/actions/authenticateAction.js
  src/redux/actions/homeFeedAction.js
Labels: feat

#107 Feat: 회원가입 예외처리 및 이미지 업로드
  src/App.jsx
  src/components/common/ProfileButtons.jsx
  src/components/profile/UserProfile.jsx
  src/pages/HomePage.jsx
  src/pages/JoinMembershipPage.jsx
  src/pages/LoginPage.jsx
  src/pages/ProfileSettingPage.jsx
  src/redux/actions/homeFeedAction.js
  src/redux/actions/joinAction.js
  src/redux/actions/joinAction.jsx
  src/redux/reducers/index.js
  src/redux/reducers/joinReducer.js
Labels: feat

#108 Perf: HomePage Link 범위 수정
  src/App.jsx
  src/components/common/HomeImgPost.jsx
  src/components/home/HomeFeedBox.jsx
Labels: feat

#113 Fix: 홈페이지 Link 중복 버그 수정
  src/components/home/HomeFeedBox.jsx
Labels: bug

#115 Feat: 상품 삭제 구현 완료
  src/components/common/Modal.jsx
  src/components/profile/UserProduct.jsx
  src/redux/actions/productAcition.js
Labels: feat

#114 Feat: 포스트 업로드 시 이미지 업로드, 이미지 서버로 전송
  src/App.jsx
  src/components/common/ProfileButtons.jsx
  src/components/common/TabMenu.jsx
  src/index.js
  src/pages/PostUploadPage.jsx
  src/redux/actions/postAction.js
  src/redux/reducers/index.js
  src/redux/reducers/postReducer.js
Labels: feat

#116 Chat page 추가
  src/App.jsx
  src/components/common/Buttons.jsx
  src/components/common/Comment.jsx
  src/components/common/HomeImgPost.jsx
  src/components/common/HomePost.jsx
  src/components/common/TabMenu.jsx
  src/components/loginOptions/LoginOptions.jsx
  src/pages/ChatItemPage.jsx
  src/pages/ChatPage.jsx
  src/pages/SplashPage.jsx
Labels: style

#117 Fix: 머지할 때 날라간 코드들 수정
  src/App.jsx
  src/components/common/ProfileButtons.jsx
  src/components/common/TabMenu.jsx
  src/pages/LoginPage.jsx
  src/redux/reducers/index.js
  src/redux/reducers/postReducer.js
Labels: bug

#118 Feat: 프로필 수정 페이지 구현
  src/App.jsx
  src/pages/ProfileModificationPage.jsx
  src/redux/actions/profileAction.js
Labels: feat

#122 Feat: 탭 기능 구현 및 TopNavLink 에러 수정
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/TabMenu.jsx
  src/components/common/TopNav.jsx
  src/components/home/HomeFeedBox.jsx
  src/components/profile/UserPost.jsx
  src/index.js
  src/pages/ChatPage.jsx
  src/pages/MyProfile.jsx
  src/redux/actions/homeFeedAction.js
  src/redux/reducers/authenticateReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/productReducer.js
  src/redux/store.js
Labels: bug, feat

#127 Test: 수정
  src/components/profile/UserPost.jsx
  src/components/profile/UserProduct.jsx
  src/components/profile/UserProfile.jsx
  src/pages/HomePage.jsx
  src/pages/PostPage.jsx
  src/pages/ProfileModificationPage.jsx
  src/redux/actions/authenticateAction.js
  src/redux/actions/homeFeedAction.js
  src/redux/actions/profileAction.js
  src/redux/reducers/authenticateReducer.js
  src/redux/reducers/homeFeedReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/profileReducer.js
Labels: bug

#126 Feat: 게시물 업로드 기능 구현
  src/pages/PostUploadPage.jsx
  src/redux/actions/commentListAction.js
  src/redux/actions/postAction.js
Labels: feat

#128 Fix: 새로고침 문제 해결
  src/components/profile/UserProfile.jsx
  src/index.js
  src/pages/HomePage.jsx
  src/redux/actions/authenticateAction.js
  src/redux/actions/homeFeedAction.js
  src/redux/reducers/authenticateReducer.js
  src/redux/reducers/index.js
  src/redux/store.js
Labels: feat

#143 Refactor: 폴더 정리
  public/index.html
  src/components/home/HomeFeed/index.jsx
  src/components/home/HomeFeed/index.style.js
  src/components/home/HomeFeedBox.jsx
  src/components/home/HomeNoFollower.jsx
  src/components/home/HomeNoFollower/index.jsx
  src/components/home/HomeNoFollower/index.style.js
  src/components/join/JoinMemberShip/index.jsx
  src/components/join/JoinMemberShip/index.style.js
  src/components/join/ProfileSetting/index.jsx
  src/components/join/ProfileSetting/index.style.js
  src/components/login/LoginMain/index.jsx
  src/components/login/LoginMain/index.style.js
  src/components/login/LoginOptions/index.jsx
  src/components/login/LoginOptions/index.style.js
  src/components/login/Splash/index.jsx
  src/components/login/Splash/index.style.js
  src/components/product/AddProduct/index.jsx
  src/components/product/AddProduct/index.style.js
  src/components/product/ProductModification/index.jsx
  src/components/product/ProductModification/index.style.js
  src/pages/AddProductPage.jsx
  src/pages/HomePage.jsx
  src/pages/JoinMembershipPage.jsx
  src/pages/LoginPage.jsx
  src/pages/ProductModificationPage.jsx
  src/pages/ProfileSettingPage.jsx
  src/pages/SplashPage.jsx
Labels: refactoring

#145 Refactor: 폴더 관리
  src/components/Splash/index.jsx
  src/components/Splash/index.style.js
  src/components/login/LoginMain/index.jsx
  src/components/login/LoginMain/index.style.js
  src/components/login/LoginOptions/index.jsx
Labels: refactoring

#158 Refactor: 세션스토리지 추가
  src/components/common/alert/index.jsx
  src/components/common/modal/index.jsx
  src/components/login/LoginMain/index.jsx
  src/components/profile/userProduct/index.jsx
  src/pages/HomePage.jsx
  src/pages/MyProfile.jsx
  src/redux/actions/authenticateAction.js
  src/redux/reducers/authenticateReducer.js
Labels: refactoring
